_target_: src.loader.default.DefaultLoader
hr_dir: data/hr
lr_dir: data/lr
split: [0.8, 0.1, 0.1]
batch_size: 64
num_workers: 4
seed: ${seed}
exts: [".png", ".jpg", ".jpeg"]

augment:
  train: [crop128, fliprot, degrade_std, cutblur]
  val: [centercrop128]
